apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ololo02/devops-lab
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true