name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
    contents: read
    packages: write

jobs:
  # 1. scan code
  scan_code:
    name: Scan code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep --config auto . --error
      

  # 1 bis. scan_secrets
  scan_secrets:
    name: Scan secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 2. test
  test_code:
    name: Test code
    needs: [scan_code, scan_secrets]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      - name: Run tests
        run: |
          pip install flask pytest
          cd app
          pytest test_app.py -v
  # 3. build
  build_code:
    name: Build code
    needs: test_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
  # 4. scan image
  scan_image:
    name: Scan image
    needs: build_code
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          format: table
          exit-code: '1'
          severity: CRITICAL,HIGH
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  # 5. push
  push_image:
    name: Push image
    needs: scan_image
    runs-on: ubuntu-latest
    steps:
      - run: echo "push coming soon"